### PR TITLE
P2022-187_ProjectCard_corrections

### PR DESCRIPTION
**Pull request by KarolCiesluk**
[go to P2022-187 task in jira](https://tracker.intive.com/jira/browse/P2022-187)

### CODE REVIEW

**Review by PiotrAdamowicz — APPROVED** [review]
You can use CSS to truncate the text: [CSS ellipsis](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/)

**Comment by KarolCiesluk** [comment]
> You can use CSS to truncate the text: [CSS ellipsis](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/)

It might be a good idea! The only concern is that with your solution the unnecessary text will always be put into DOM too but maybe that's not a problem. I will change it and we will see what the others say 😄

**Comment by PiotrAdamowicz** [comment]
No, don't change it. If your solution works as it is leave it. It was just
a sugesstion ;)

niedz., 13 lut 2022, 11:34 użytkownik Karol Cieśluk <
***@***.***> napisał:

**Comment by KarolCiesluk** [comment]
> No, don't change it. If your solution works as it is leave it. It was just
a sugesstion ;)

Haha. Just changed it 😛 Have a look!

**Review by PiotrAdamowicz — APPROVED** [review]

**Pull request merged**
